### ISSUE TITLE
Integrate into platform.ui

### ISSUE THREAD

**Issue by vogella** [eclipselabs/default-text-editor#1]
I think this should be integrated into platform.ui

**Comment by kaloyan-raev** [comment]
I totally agree :-)

However, while I was looking for a solution to this problem, I found that they are quite some opinions how this should be implemented. So I decided to have this project as a playground. When we have a solution that fits everyone we can push this to the Platform.

The respective Eclipse bug should be: https://bugs.eclipse.org/bugs/show_bug.cgi?id=142228

**Comment by vogella** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=90292 looks also like a
fitting bug.

If you can upload a Gerrit change to the existing IDE plugin, we try to
review it with priority. Most likely this is to late for 4.5 but early 4.6
would be great.
Am 22.04.2015 8:51 vorm. schrieb "Kaloyan Raev" notifications@github.com:

**Comment by kaloyan-raev** [comment]
Patch: https://git.eclipse.org/r/46341
